# Retail Messy Dataset

In [32]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
#data load
df=pd.read_csv("retail_store_sales.csv")
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [34]:
df.info()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [35]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [36]:
df.isnull().sum().sort_values(ascending=False)

Discount Applied    4199
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Transaction ID         0
Customer ID            0
Category               0
Payment Method         0
Location               0
Transaction Date       0
dtype: int64

In [37]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

### Discount Applied column set

In [38]:
df["Discount Applied"].fillna(df["Discount Applied"].mode()[0],inplace=True)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_8640\3500191232.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Discount Applied"].fillna(df["Discount Applied"].mode()[0],inplace=True)
C:\Users\uzaif\AppData\Local\Temp\ipykernel_8640\3500191232.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Discount Applied"].fillna(df["Discount Applied"].mode()[0],inplace=True)

### Item column set

In [39]:
df["Item"].fillna(df["Item"].mode()[0],inplace=True)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_8640\1286566123.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Item"].fillna(df["Item"].mode()[0],inplace=True)

### Price Per Unit column set

In [40]:
df["Price Per Unit"].fillna(df["Price Per Unit"].mean(),inplace=True)
round(df["Price Per Unit"], 2)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_8640\706603105.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price Per Unit"].fillna(df["Price Per Unit"].mean(),inplace=True)

0        18.5
1        29.0
2        21.5
3        27.5
4        12.5
         ...
12570    38.0
12571     6.5
12572    14.0
12573    14.0
12574    17.0
Name: Price Per Unit, Length: 12575, dtype: float64

### Quantity column set

In [41]:
df["Quantity"].fillna(df["Quantity"].mean(),inplace=True)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_8640\3500112416.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Quantity"].fillna(df["Quantity"].mean(),inplace=True)

In [42]:
df["Quantity"]=df["Quantity"].astype(int)

### Total Spent column set

In [43]:
df["Total Spent"].fillna(df["Total Spent"].mean(),inplace=True)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_8640\1333721050.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total Spent"].fillna(df["Total Spent"].mean(),inplace=True)

### Customer ID sequences set

In [44]:
df.sort_values("Customer ID",ascending=True,inplace=True)

In [45]:
df["Customer ID"].duplicated()

1631     False
10084     True
440       True
6082      True
5245      True
         ...
5248      True
2657      True
10663     True
10964     True
5251      True
Name: Customer ID, Length: 12575, dtype: bool

In [46]:
store=[]
for i in range(12575):
    store.append("Cust_"+str(i))
print(store)

['Cust_0', 'Cust_1', 'Cust_2', 'Cust_3', 'Cust_4', 'Cust_5', 'Cust_6', 'Cust_7', 'Cust_8', 'Cust_9', 'Cust_10', 'Cust_11', 'Cust_12', 'Cust_13', 'Cust_14', 'Cust_15', 'Cust_16', 'Cust_17', 'Cust_18', 'Cust_19', 'Cust_20', 'Cust_21', 'Cust_22', 'Cust_23', 'Cust_24', 'Cust_25', 'Cust_26', 'Cust_27', 'Cust_28', 'Cust_29', 'Cust_30', 'Cust_31', 'Cust_32', 'Cust_33', 'Cust_34', 'Cust_35', 'Cust_36', 'Cust_37', 'Cust_38', 'Cust_39', 'Cust_40', 'Cust_41', 'Cust_42', 'Cust_43', 'Cust_44', 'Cust_45', 'Cust_46', 'Cust_47', 'Cust_48', 'Cust_49', 'Cust_50', 'Cust_51', 'Cust_52', 'Cust_53', 'Cust_54', 'Cust_55', 'Cust_56', 'Cust_57', 'Cust_58', 'Cust_59', 'Cust_60', 'Cust_61', 'Cust_62', 'Cust_63', 'Cust_64', 'Cust_65', 'Cust_66', 'Cust_67', 'Cust_68', 'Cust_69', 'Cust_70', 'Cust_71', 'Cust_72', 'Cust_73', 'Cust_74', 'Cust_75', 'Cust_76', 'Cust_77', 'Cust_78', 'Cust_79', 'Cust_80', 'Cust_81', 'Cust_82', 'Cust_83', 'Cust_84', 'Cust_85', 'Cust_86', 'Cust_87', 'Cust_88', 'Cust_89', 'Cust_90', 'Cust_91', 'Cust_92', 'Cust_93', 'Cust_94', 'Cust_95', 'Cust_96', 'Cust_97', 'Cust_98', 'Cust_99', 'Cust_100', 'Cust_101', 'Cust_102', 'Cust_103', 'Cust_104', 'Cust_105', 'Cust_106', 'Cust_107', 'Cust_108', 'Cust_109', 'Cust_110', 'Cust_111', 'Cust_112', 'Cust_113', 'Cust_114', 'Cust_115', 'Cust_116', 'Cust_117', 'Cust_118', 'Cust_119', 'Cust_120', 'Cust_121', 'Cust_122', 'Cust_123', 'Cust_124', 'Cust_125', 'Cust_126', 'Cust_127', 'Cust_128', 'Cust_129', 'Cust_130', 'Cust_131', 'Cust_132', 'Cust_133', 'Cust_134', 'Cust_135', 'Cust_136', 'Cust_137', 'Cust_138', 'Cust_139', 'Cust_140', 'Cust_141', 'Cust_142', 'Cust_143', 'Cust_144', 'Cust_145', 'Cust_146', 'Cust_147', 'Cust_148', 'Cust_149', 'Cust_150', 'Cust_151', 'Cust_152', 'Cust_153', 'Cust_154', 'Cust_155', 'Cust_156', 'Cust_157', 'Cust_158', 'Cust_159', 'Cust_160', 'Cust_161', 'Cust_162', 'Cust_163', 'Cust_164', 'Cust_165', 'Cust_166', 'Cust_167', 'Cust_168', 'Cust_169', 'Cust_170', 'Cust_171', 'Cust_172', 'Cust_173', 'Cust_174', 'Cust_175', 'Cust_176', 'Cust_177', 'Cust_178', 'Cust_179', 'Cust_180', 'Cust_181', 'Cust_182', 'Cust_183', 'Cust_184', 'Cust_185', 'Cust_186', 'Cust_187', 'Cust_188', 'Cust_189', 'Cust_190', 'Cust_191', 'Cust_192', 'Cust_193', 'Cust_194', 'Cust_195', 'Cust_196', 'Cust_197', 'Cust_198', 'Cust_199', 'Cust_200', 'Cust_201', 'Cust_202', 'Cust_203', 'Cust_204', 'Cust_205', 'Cust_206', 'Cust_207', 'Cust_208', 'Cust_209', 'Cust_210', 'Cust_211', 'Cust_212', 'Cust_213', 'Cust_214', 'Cust_215', 'Cust_216', 'Cust_217', 'Cust_218', 'Cust_219', 'Cust_220', 'Cust_221', 'Cust_222', 'Cust_223', 'Cust_224', 'Cust_225', 'Cust_226', 'Cust_227', 'Cust_228', 'Cust_229', 'Cust_230', 'Cust_231', 'Cust_232', 'Cust_233', 'Cust_234', 'Cust_235', 'Cust_236', 'Cust_237', 'Cust_238', 'Cust_239', 'Cust_240', 'Cust_241', 'Cust_242', 'Cust_243', 'Cust_244', 'Cust_245', 'Cust_246', 'Cust_247', 'Cust_248', 'Cust_249', 'Cust_250', 'Cust_251', 'Cust_252', 'Cust_253', 'Cust_254', 'Cust_255', 'Cust_256', 'Cust_257', 'Cust_258', 'Cust_259', 'Cust_260', 'Cust_261', 'Cust_262', 'Cust_263', 'Cust_264', 'Cust_265', 'Cust_266', 'Cust_267', 'Cust_268', 'Cust_269', 'Cust_270', 'Cust_271', 'Cust_272', 'Cust_273', 'Cust_274', 'Cust_275', 'Cust_276', 'Cust_277', 'Cust_278', 'Cust_279', 'Cust_280', 'Cust_281', 'Cust_282', 'Cust_283', 'Cust_284', 'Cust_285', 'Cust_286', 'Cust_287', 'Cust_288', 'Cust_289', 'Cust_290', 'Cust_291', 'Cust_292', 'Cust_293', 'Cust_294', 'Cust_295', 'Cust_296', 'Cust_297', 'Cust_298', 'Cust_299', 'Cust_300', 'Cust_301', 'Cust_302', 'Cust_303', 'Cust_304', 'Cust_305', 'Cust_306', 'Cust_307', 'Cust_308', 'Cust_309', 'Cust_310', 'Cust_311', 'Cust_312', 'Cust_313', 'Cust_314', 'Cust_315', 'Cust_316', 'Cust_317', 'Cust_318', 'Cust_319', 'Cust_320', 'Cust_321', 'Cust_322', 'Cust_323', 'Cust_324', 'Cust_325', 'Cust_326', 'Cust_327', 'Cust_328', 'Cust_329', 'Cust_330', 'Cust_331', 'Cust_332', 'Cust_333', 'Cust_334', 'Cust_335', 'Cust_336', 'Cust_337', 'Cust_338', 'Cust_339', 'Cust_340', 'Cust_341', 'Cust_342', 'Cust_343', 'Cust_344', 'Cust_345', 'Cust_346', 'Cust_347', 'Cust_348', 'Cust_349', 'Cust_350', 'Cust_351', 'Cust_352', 'Cust_353', 'Cust_354', 'Cust_355', 'Cust_356', 'Cust_357', 'Cust_358', 'Cust_359', 'Cust_360', 'Cust_361', 'Cust_362', 'Cust_363', 'Cust_364', 'Cust_365', 'Cust_366', 'Cust_367', 'Cust_368', 'Cust_369', 'Cust_370', 'Cust_371', 'Cust_372', 'Cust_373', 'Cust_374', 'Cust_375', 'Cust_376', 'Cust_377', 'Cust_378', 'Cust_379', 'Cust_380', 'Cust_381', 'Cust_382', 'Cust_383', 'Cust_384', 'Cust_385', 'Cust_386', 'Cust_387', 'Cust_388', 'Cust_389', 'Cust_390', 'Cust_391', 'Cust_392', 'Cust_393', 'Cust_394', 'Cust_395', 'Cust_396', 'Cust_397', 'Cust_398', 'Cust_399', 'Cust_400', 'Cust_401', 'Cust_402', 'Cust_403', 'Cust_404', 'Cust_405', 'Cust_406', 'Cust_407', 'Cust_408', 'Cust_409', 'Cust_410', 'Cust_411', 'Cust_412', 'Cust_413', 'Cust_414', 'Cust_415', 'Cust_416', 'Cust_417', 'Cust_418', 'Cust_419', 'Cust_420', 'Cust_421', 'Cust_422', 'Cust_423', 'Cust_424', 'Cust_425', 'Cust_426', 'Cust_427', 'Cust_428', 'Cust_429', 'Cust_430', 'Cust_431', 'Cust_432', 'Cust_433', 'Cust_434', 'Cust_435', 'Cust_436', 'Cust_437', 'Cust_438', 'Cust_439', 'Cust_440', 'Cust_441', 'Cust_442', 'Cust_443', 'Cust_444', 'Cust_445', 'Cust_446', 'Cust_447', 'Cust_448', 'Cust_449', 'Cust_450', 'Cust_451', 'Cust_452', 'Cust_453', 'Cust_454', 'Cust_455', 'Cust_456', 'Cust_457', 'Cust_458', 'Cust_459', 'Cust_460', 'Cust_461', 'Cust_462', 'Cust_463', 'Cust_464', 'Cust_465', 'Cust_466', 'Cust_467', 'Cust_468', 'Cust_469', 'Cust_470', 'Cust_471', 'Cust_472', 'Cust_473', 'Cust_474', 'Cust_475', 'Cust_476', 'Cust_477', 'Cust_478', 'Cust_479', 'Cust_480', 'Cust_481', 'Cust_482', 'Cust_483', 'Cust_484', 'Cust_485', 'Cust_486', 'Cust_487', 'Cust_488', 'Cust_489', 'Cust_490', 'Cust_491', 'Cust_492', 'Cust_493', 'Cust_494', 'Cust_495', 'Cust_496', 'Cust_497', 'Cust_498', 'Cust_499', 'Cust_500', 'Cust_501', 'Cust_502', 'Cust_503', 'Cust_504', 'Cust_505', 'Cust_506', 'Cust_507', 'Cust_508', 'Cust_509', 'Cust_510', 'Cust_511', 'Cust_512', 'Cust_513', 'Cust_514', 'Cust_515', 'Cust_516', 'Cust_517', 'Cust_518', 'Cust_519', 'Cust_520', 'Cust_521', 'Cust_522', 'Cust_523', 'Cust_524', 'Cust_525', 'Cust_526', 'Cust_527', 'Cust_528', 'Cust_529', 'Cust_530', 'Cust_531', 'Cust_532', 'Cust_533', 'Cust_534', 'Cust_535', 'Cust_536', 'Cust_537', 'Cust_538', 'Cust_539', 'Cust_540', 'Cust_541', 'Cust_542', 'Cust_543', 'Cust_544', 'Cust_545', 'Cust_546', 'Cust_547', 'Cust_548', 'Cust_549', 'Cust_550', 'Cust_551', 'Cust_552', 'Cust_553', 'Cust_554', 'Cust_555', 'Cust_556', 'Cust_557', 'Cust_558', 'Cust_559', 'Cust_560', 'Cust_561', 'Cust_562', 'Cust_563', 'Cust_564', 'Cust_565', 'Cust_566', 'Cust_567', 'Cust_568', 'Cust_569', 'Cust_570', 'Cust_571', 'Cust_572', 'Cust_573', 'Cust_574', 'Cust_575', 'Cust_576', 'Cust_577', 'Cust_578', 'Cust_579', 'Cust_580', 'Cust_581', 'Cust_582', 'Cust_583', 'Cust_584', 'Cust_585', 'Cust_586', 'Cust_587', 'Cust_588', 'Cust_589', 'Cust_590', 'Cust_591', 'Cust_592', 'Cust_593', 'Cust_594', 'Cust_595', 'Cust_596', 'Cust_597', 'Cust_598', 'Cust_599', 'Cust_600', 'Cust_601', 'Cust_602', 'Cust_603', 'Cust_604', 'Cust_605', 'Cust_606', 'Cust_607', 'Cust_608', 'Cust_609', 'Cust_610', 'Cust_611', 'Cust_612', 'Cust_613', 'Cust_614', 'Cust_615', 'Cust_616', 'Cust_617', 'Cust_618', 'Cust_619', 'Cust_620', 'Cust_621', 'Cust_622', 'Cust_623', 'Cust_624', 'Cust_625', 'Cust_626', 'Cust_627', 'Cust_628', 'Cust_629', 'Cust_630', 'Cust_631', 'Cust_632', 'Cust_633', 'Cust_634', 'Cust_635', 'Cust_636', 'Cust_637', 'Cust_638', 'Cust_639', 'Cust_640', 'Cust_641', 'Cust_642', 'Cust_643', 'Cust_644', 'Cust_645', 'Cust_646', 'Cust_647', 'Cust_648', 'Cust_649', 'Cust_650', 'Cust_651', 'Cust_652', 'Cust_653', 'Cust_654', 'Cust_655', 'Cust_656', 'Cust_657', 'Cust_658', 'Cust_659', 'Cust_660', 'Cust_661', 'Cust_662', 'Cust_663', 'Cust_664', 'Cust_665', 'Cust_666', 'Cust_667', 'Cust_668', 'Cust_669', 'Cust_670', 'Cust_671', 'Cust_672', 'Cust_673', 'Cust_674', 'Cust_675', 'Cust_676', 'Cust_677', 'Cust_678', 'Cust_679', 'Cust_680', 'Cust_681', 'Cust_682', 'Cust_683', 'Cust_684', 'Cust_685', 'Cust_686', 'Cust_687', 'Cust_688', 'Cust_689', 'Cust_690', 'Cust_691', 'Cust_692', 'Cust_693', 'Cust_694', 'Cust_695', 'Cust_696', 'Cust_697', 'Cust_698', 'Cust_699', 'Cust_700', 'Cust_701', 'Cust_702', 'Cust_703', 'Cust_704', 'Cust_705', 'Cust_706', 'Cust_707', 'Cust_708', 'Cust_709', 'Cust_710', 'Cust_711', 'Cust_712', 'Cust_713', 'Cust_714', 'Cust_715', 'Cust_716', 'Cust_717', 'Cust_718', 'Cust_719', 'Cust_720', 'Cust_721', 'Cust_722', 'Cust_723', 'Cust_724', 'Cust_725', 'Cust_726', 'Cust_727', 'Cust_728', 'Cust_729', 'Cust_730', 'Cust_731', 'Cust_732', 'Cust_733', 'Cust_734', 'Cust_735', 'Cust_736', 'Cust_737', 'Cust_738', 'Cust_739', 'Cust_740', 'Cust_741', 'Cust_742', 'Cust_743', 'Cust_744', 'Cust_745', 'Cust_746', 'Cust_747', 'Cust_748', 'Cust_749', 'Cust_750', 'Cust_751', 'Cust_752', 'Cust_753', 'Cust_754', 'Cust_755', 'Cust_756', 'Cust_757', 'Cust_758', 'Cust_759', 'Cust_760', 'Cust_761', 'Cust_762', 'Cust_763', 'Cust_764', 'Cust_765', 'Cust_766', 'Cust_767', 'Cust_768', 'Cust_769', 'Cust_770', 'Cust_771', 'Cust_772', 'Cust_773', 'Cust_774', 'Cust_775', 'Cust_776', 'Cust_777', 'Cust_778', 'Cust_779', 'Cust_780', 'Cust_781', 'Cust_782', 'Cust_783', 'Cust_784', 'Cust_785', 'Cust_786', 'Cust_787', 'Cust_788', 'Cust_789', 'Cust_790', 'Cust_791', 'Cust_792', 'Cust_793', 'Cust_794', 'Cust_795', 'Cust_796', 'Cust_797', 'Cust_798', 'Cust_799', 'Cust_800', 'Cust_801', 'Cust_802', 'Cust_803', 'Cust_804', 'Cust_805', 'Cust_806', 'Cust_807', 'Cust_808', 'Cust_809', 'Cust_810', 'Cust_811', 'Cust_812', 'Cust_813', 'Cust_814', 'Cust_815', 'Cust_816', 'Cust_817', 'Cust_818', 'Cust_819', 'Cust_820', 'Cust_821', 'Cust_822', 'Cust_823', 'Cust_824', 'Cust_825', 'Cust_826', 'Cust_827', 'Cust_828', 'Cust_829', 'Cust_830', 'Cust_831', 'Cust_832', 'Cust_833', 'Cust_834', 'Cust_835', 'Cust_836', 'Cust_837', 'Cust_838', 'Cust_839', 'Cust_840', 'Cust_841', 'Cust_842', 'Cust_843', 'Cust_844', 'Cust_845', 'Cust_846', 'Cust_847', 'Cust_848', 'Cust_849', 'Cust_850', 'Cust_851', 'Cust_852', 'Cust_853', 'Cust_854', 'Cust_855', 'Cust_856', 'Cust_857', 'Cust_858', 'Cust_859', 'Cust_860', 'Cust_861', 'Cust_862', 'Cust_863', 'Cust_864', 'Cust_865', 'Cust_866', 'Cust_867', 'Cust_868', 'Cust_869', 'Cust_870', 'Cust_871', 'Cust_872', 'Cust_873', 'Cust_874', 'Cust_875', 'Cust_876', 'Cust_877', 'Cust_878', 'Cust_879', 'Cust_880', 'Cust_881', 'Cust_882', 'Cust_883', 'Cust_884', 'Cust_885', 'Cust_886', 'Cust_887', 'Cust_888', 'Cust_889', 'Cust_890', 'Cust_891', 'Cust_892', 'Cust_893', 'Cust_894', 'Cust_895', 'Cust_896', 'Cust_897', 'Cust_898', 'Cust_899', 'Cust_900', 'Cust_901', 'Cust_902', 'Cust_903', 'Cust_904', 'Cust_905', 'Cust_906', 'Cust_907', 'Cust_908', 'Cust_909', 'Cust_910', 'Cust_911', 'Cust_912', 'Cust_913', 'Cust_914', 'Cust_915', 'Cust_916', 'Cust_917', 'Cust_918', 'Cust_919', 'Cust_920', 'Cust_921', 'Cust_922', 'Cust_923', 'Cust_924', 'Cust_925', 'Cust_926', 'Cust_927', 'Cust_928', 'Cust_929', 'Cust_930', 'Cust_931', 'Cust_932', 'Cust_933', 'Cust_934', 'Cust_935', 'Cust_936', 'Cust_937', 'Cust_938', 'Cust_939', 'Cust_940', 'Cust_941', 'Cust_942', 'Cust_943', 'Cust_944', 'Cust_945', 'Cust_946', 'Cust_947', 'Cust_948', 'Cust_949', 'Cust_950', 'Cust_951', 'Cust_952', 'Cust_953', 'Cust_954', 'Cust_955', 'Cust_956', 'Cust_957', 'Cust_958', 'Cust_959', 'Cust_960', 'Cust_961', 'Cust_962', 'Cust_963', 'Cust_964', 'Cust_965', 'Cust_966', 'Cust_967', 'Cust_968', 'Cust_969', 'Cust_970', 'Cust_971', 'Cust_972', 'Cust_973', 'Cust_974', 'Cust_975', 'Cust_976', 'Cust_977', 'Cust_978', 'Cust_979', 'Cust_980', 'Cust_981', 'Cust_982', 'Cust_983', 'Cust_984', 'Cust_985', 'Cust_986', 'Cust_987', 'Cust_988', 'Cust_989', 'Cust_990', 'Cust_991', 'Cust_992', 'Cust_993', 'Cust_994', 'Cust_995', 'Cust_996', 'Cust_997', 'Cust_998', 'Cust_999', 'Cust_1000', 'Cust_1001', 'Cust_1002', 'Cust_1003', 'Cust_1004', 'Cust_1005', 'Cust_1006', 'Cust_1007', 'Cust_1008', 'Cust_1009', 'Cust_1010', 'Cust_1011', 'Cust_1012', 'Cust_1013', 'Cust_1014', 'Cust_1015', 'Cust_1016', 'Cust_1017', 'Cust_1018', 'Cust_1019', 'Cust_1020', 'Cust_1021', 'Cust_1022', 'Cust_1023', 'Cust_1024', 'Cust_1025', 'Cust_1026', 'Cust_1027', 'Cust_1028', 'Cust_1029', 'Cust_1030', 'Cust_1031', 'Cust_1032', 'Cust_1033', 'Cust_1034', 'Cust_1035', 'Cust_1036', 'Cust_1037', 'Cust_1038', 'Cust_1039', 'Cust_1040', 'Cust_1041', 'Cust_1042', 'Cust_1043', 'Cust_1044', 'Cust_1045', 'Cust_1046', 'Cust_1047', 'Cust_1048', 'Cust_1049', 'Cust_1050', 'Cust_1051', 'Cust_1052', 'Cust_1053', 'Cust_1054', 'Cust_1055', 'Cust_1056', 'Cust_1057', 'Cust_1058', 'Cust_1059', 'Cust_1060', 'Cust_1061', 'Cust_1062', 'Cust_1063', 'Cust_1064', 'Cust_1065', 'Cust_1066', 'Cust_1067', 'Cust_1068', 'Cust_1069', 'Cust_1070', 'Cust_1071', 'Cust_1072', 'Cust_1073', 'Cust_1074', 'Cust_1075', 'Cust_1076', 'Cust_1077', 'Cust_1078', 'Cust_1079', 'Cust_1080', 'Cust_1081', 'Cust_1082', 'Cust_1083', 'Cust_1084', 'Cust_1085', 'Cust_1086', 'Cust_1087', 'Cust_1088', 'Cust_1089', 'Cust_1090', 'Cust_1091', 'Cust_1092', 'Cust_1093', 'Cust_1094', 'Cust_1095', 'Cust_1096', 'Cust_1097', 'Cust_1098', 'Cust_1099', 'Cust_1100', 'Cust_1101', 'Cust_1102', 'Cust_1103', 'Cust_1104', 'Cust_1105', 'Cust_1106', 'Cust_1107', 'Cust_1108', 'Cust_1109', 'Cust_1110', 'Cust_1111', 'Cust_1112', 'Cust_1113', 'Cust_1114', 'Cust_1115', 'Cust_1116', 'Cust_1117', 'Cust_1118', 'Cust_1119', 'Cust_1120', 'Cust_1121', 'Cust_1122', 'Cust_1123', 'Cust_1124', 'Cust_1125', 'Cust_1126', 'Cust_1127', 'Cust_1128', 'Cust_1129', 'Cust_1130', 'Cust_1131', 'Cust_1132', 'Cust_1133', 'Cust_1134', 'Cust_1135', 'Cust_1136', 'Cust_1137', 'Cust_1138', 'Cust_1139', 'Cust_1140', 'Cust_1141', 'Cust_1142', 'Cust_1143', 'Cust_1144', 'Cust_1145', 'Cust_1146', 'Cust_1147', 'Cust_1148', 'Cust_1149', 'Cust_1150', 'Cust_1151', 'Cust_1152', 'Cust_1153', 'Cust_1154', 'Cust_1155', 'Cust_1156', 'Cust_1157', 'Cust_1158', 'Cust_1159', 'Cust_1160', 'Cust_1161', 'Cust_1162', 'Cust_1163', 'Cust_1164', 'Cust_1165', 'Cust_1166', 'Cust_1167', 'Cust_1168', 'Cust_1169', 'Cust_1170', 'Cust_1171', 'Cust_1172', 'Cust_1173', 'Cust_1174', 'Cust_1175', 'Cust_1176', 'Cust_1177', 'Cust_1178', 'Cust_1179', 'Cust_1180', 'Cust_1181', 'Cust_1182', 'Cust_1183', 'Cust_1184', 'Cust_1185', 'Cust_1186', 'Cust_1187', 'Cust_1188', 'Cust_1189', 'Cust_1190', 'Cust_1191', 'Cust_1192', 'Cust_1193', 'Cust_1194', 'Cust_1195', 'Cust_1196', 'Cust_1197', 'Cust_1198', 'Cust_1199', 'Cust_1200', 'Cust_1201', 'Cust_1202', 'Cust_1203', 'Cust_1204', 'Cust_1205', 'Cust_1206', 'Cust_1207', 'Cust_1208', 'Cust_1209', 'Cust_1210', 'Cust_1211', 'Cust_1212', 'Cust_1213', 'Cust_1214', 'Cust_1215', 'Cust_1216', 'Cust_1217', 'Cust_1218', 'Cust_1219', 'Cust_1220', 'Cust_1221', 'Cust_1222', 'Cust_1223', 'Cust_1224', 'Cust_1225', 'Cust_1226', 'Cust_1227', 'Cust_1228', 'Cust_1229', 'Cust_1230', 'Cust_1231', 'Cust_1232', 'Cust_1233', 'Cust_1234', 'Cust_1235', 'Cust_1236', 'Cust_1237', 'Cust_1238', 'Cust_1239', 'Cust_1240', 'Cust_1241', 'Cust_1242', 'Cust_1243', 'Cust_1244', 'Cust_1245', 'Cust_1246', 'Cust_1247', 'Cust_1248', 'Cust_1249', 'Cust_1250', 'Cust_1251', 'Cust_1252', 'Cust_1253', 'Cust_1254', 'Cust_1255', 'Cust_1256', 'Cust_1257', 'Cust_1258', 'Cust_1259', 'Cust_1260', 'Cust_1261', 'Cust_1262', 'Cust_1263', 'Cust_1264', 'Cust_1265', 'Cust_1266', 'Cust_1267', 'Cust_1268', 'Cust_1269', 'Cust_1270', 'Cust_1271', 'Cust_1272', 'Cust_1273', 'Cust_1274', 'Cust_1275', 'Cust_1276', 'Cust_1277', 'Cust_1278', 'Cust_1279', 'Cust_1280', 'Cust_1281', 'Cust_1282', 'Cust_1283', 'Cust_1284', 'Cust_1285', 'Cust_1286', 'Cust_1287', 'Cust_1288', 'Cust_1289', 'Cust_1290', 'Cust_1291', 'Cust_1292', 'Cust_1293', 'Cust_1294', 'Cust_1295', 'Cust_1296', 'Cust_1297', 'Cust_1298', 'Cust_1299', 'Cust_1300', 'Cust_1301', 'Cust_1302', 'Cust_1303', 'Cust_1304', 'Cust_1305', 'Cust_1306', 'Cust_1307', 'Cust_1308', 'Cust_1309', 'Cust_1310', 'Cust_1311', 'Cust_1312', 'Cust_1313', 'Cust_1314', 'Cust_1315', 'Cust_1316', 'Cust_1317', 'Cust_1318', 'Cust_1319', 'Cust_1320', 'Cust_1321', 'Cust_1322', 'Cust_1323', 'Cust_1324', 'Cust_1325', 'Cust_1326', 'Cust_1327', 'Cust_1328', 'Cust_1329', 'Cust_1330', 'Cust_1331', 'Cust_1332', 'Cust_1333', 'Cust_1334', 'Cust_1335', 'Cust_1336', 'Cust_1337', 'Cust_1338', 'Cust_1339', 'Cust_1340', 'Cust_1341', 'Cust_1342', 'Cust_1343', 'Cust_1344', 'Cust_1345', 'Cust_1346', 'Cust_1347', 'Cust_1348', 'Cust_1349', 'Cust_1350', 'Cust_1351', 'Cust_1352', 'Cust_1353', 'Cust_1354', 'Cust_1355', 'Cust_1356', 'Cust_1357', 'Cust_1358', 'Cust_1359', 'Cust_1360', 'Cust_1361', 'Cust_1362', 'Cust_1363', 'Cust_1364', 'Cust_1365', 'Cust_1366', 'Cust_1367', 'Cust_1368', 'Cust_1369', 'Cust_1370', 'Cust_1371', 'Cust_1372', 'Cust_1373', 'Cust_1374', 'Cust_1375', 'Cust_1376', 'Cust_1377', 'Cust_1378', 'Cust_1379', 'Cust_1380', 'Cust_1381', 'Cust_1382', 'Cust_1383', 'Cust_1384', 'Cust_1385', 'Cust_1386', 'Cust_1387', 'Cust_1388', 'Cust_1389', 'Cust_1390', 'Cust_1391', 'Cust_1392', 'Cust_1393', 'Cust_1394', 'Cust_1395', 'Cust_1396', 'Cust_1397', 'Cust_1398', 'Cust_1399', 'Cust_1400', 'Cust_1401', 'Cust_1402', 'Cust_1403', 'Cust_1404', 'Cust_1405', 'Cust_1406', 'Cust_1407', 'Cust_1408', 'Cust_1409', 'Cust_1410', 'Cust_1411', 'Cust_1412', 'Cust_1413', 'Cust_1414', 'Cust_1415', 'Cust_1416', 'Cust_1417', 'Cust_1418', 'Cust_1419', 'Cust_1420', 'Cust_1421', 'Cust_1422', 'Cust_1423', 'Cust_1424', 'Cust_1425', 'Cust_1426', 'Cust_1427', 'Cust_1428', 'Cust_1429', 'Cust_1430', 'Cust_1431', 'Cust_1432', 'Cust_1433', 'Cust_1434', 'Cust_1435', 'Cust_1436', 'Cust_1437', 'Cust_1438', 'Cust_1439', 'Cust_1440', 'Cust_1441', 'Cust_1442', 'Cust_1443', 'Cust_1444', 'Cust_1445', 'Cust_1446', 'Cust_1447', 'Cust_1448', 'Cust_1449', 'Cust_1450', 'Cust_1451', 'Cust_1452', 'Cust_1453', 'Cust_1454', 'Cust_1455', 'Cust_1456', 'Cust_1457', 'Cust_1458', 'Cust_1459', 'Cust_1460', 'Cust_1461', 'Cust_1462', 'Cust_1463', 'Cust_1464', 'Cust_1465', 'Cust_1466', 'Cust_1467', 'Cust_1468', 'Cust_1469', 'Cust_1470', 'Cust_1471', 'Cust_1472', 'Cust_1473', 'Cust_1474', 'Cust_1475', 'Cust_1476', 'Cust_1477', 'Cust_1478', 'Cust_1479', 'Cust_1480', 'Cust_1481', 'Cust_1482', 'Cust_1483', 'Cust_1484', 'Cust_1485', 'Cust_1486', 'Cust_1487', 'Cust_1488', 'Cust_1489', 'Cust_1490', 'Cust_1491', 'Cust_1492', 'Cust_1493', 'Cust_1494', 'Cust_1495', 'Cust_1496', 'Cust_1497', 'Cust_1498', 'Cust_1499', 'Cust_1500', 'Cust_1501', 'Cust_1502', 'Cust_1503', 'Cust_1504', 'Cust_1505', 'Cust_1506', 'Cust_1507', 'Cust_1508', 'Cust_1509', 'Cust_1510', 'Cust_1511', 'Cust_1512', 'Cust_1513', 'Cust_1514', 'Cust_1515', 'Cust_1516', 'Cust_1517', 'Cust_1518', 'Cust_1519', 'Cust_1520', 'Cust_1521', 'Cust_1522', 'Cust_1523', 'Cust_1524', 'Cust_1525', 'Cust_1526', 'Cust_1527', 'Cust_1528', 'Cust_1529', 'Cust_1530', 'Cust_1531', 'Cust_1532', 'Cust_1533', 'Cust_1534', 'Cust_1535', 'Cust_1536', 'Cust_1537', 'Cust_1538', 'Cust_1539', 'Cust_1540', 'Cust_1541', 'Cust_1542', 'Cust_1543', 'Cust_1544', 'Cust_1545', 'Cust_1546', 'Cust_1547', 'Cust_1548', 'Cust_1549', 'Cust_1550', 'Cust_1551', 'Cust_1552', 'Cust_1553', 'Cust_1554', 'Cust_1555', 'Cust_1556', 'Cust_1557', 'Cust_1558', 'Cust_1559', 'Cust_1560', 'Cust_1561', 'Cust_1562', 'Cust_1563', 'Cust_1564', 'Cust_1565', 'Cust_1566', 'Cust_1567', 'Cust_1568', 'Cust_1569', 'Cust_1570', 'Cust_1571', 'Cust_1572', 'Cust_1573', 'Cust_1574', 'Cust_1575', 'Cust_1576', 'Cust_1577', 'Cust_1578', 'Cust_1579', 'Cust_1580', 'Cust_1581', 'Cust_1582', 'Cust_1583', 'Cust_1584', 'Cust_1585', 'Cust_1586', 'Cust_1587', 'Cust_1588', 'Cust_1589', 'Cust_1590', 'Cust_1591', 'Cust_1592', 'Cust_1593', 'Cust_1594', 'Cust_1595', 'Cust_1596', 'Cust_1597', 'Cust_1598', 'Cust_1599', 'Cust_1600', 'Cust_1601', 'Cust_1602', 'Cust_1603', 'Cust_1604', 'Cust_1605', 'Cust_1606', 'Cust_1607', 'Cust_1608', 'Cust_1609', 'Cust_1610', 'Cust_1611', 'Cust_1612', 'Cust_1613', 'Cust_1614', 'Cust_1615', 'Cust_1616', 'Cust_1617', 'Cust_1618', 'Cust_1619', 'Cust_1620', 'Cust_1621', 'Cust_1622', 'Cust_1623

In [47]:
df["Customer ID"]=store

In [48]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
1631,TXN_5974928,Cust_0,Patisserie,Item_3_PAT,8.0,7,56.0,Digital Wallet,In-store,2024-09-01,True
10084,TXN_8611391,Cust_1,Beverages,Item_20_BEV,33.5,1,33.5,Credit Card,Online,2023-03-24,True
440,TXN_1619388,Cust_2,Computers and electric accessories,Item_15_CEA,26.0,1,26.0,Digital Wallet,Online,2024-05-23,True
6082,TXN_8103030,Cust_3,Furniture,Item_11_FUR,20.0,4,80.0,Cash,Online,2024-08-27,False
5245,TXN_1229733,Cust_4,Food,Item_3_FOOD,8.0,6,48.0,Digital Wallet,Online,2024-04-17,False

In [49]:
df.to_csv("new_retail_data.csv",index=False)

In [50]:
df.to_excel("new_retail_data.xlsx",index=False)

In [51]:
df[["Price Per Unit", "Total Spent"]] = df[["Price Per Unit", "Total Spent"]].round(2)

In [52]:
df["Price Per Unit"]*df["Quantity"]

1631      56.0
10084     33.5
440       26.0
6082      80.0
5245      48.0
         ...
5248      55.0
2657      92.5
10663     75.0
10964     64.0
5251     170.0
Length: 12575, dtype: float64

In [53]:
df["Transaction Date"]=pd.to_datetime(df["Transaction Date"],errors='coerce')

In [54]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
1631,TXN_5974928,Cust_0,Patisserie,Item_3_PAT,8.0,7,56.0,Digital Wallet,In-store,2024-09-01,True
10084,TXN_8611391,Cust_1,Beverages,Item_20_BEV,33.5,1,33.5,Credit Card,Online,2023-03-24,True
440,TXN_1619388,Cust_2,Computers and electric accessories,Item_15_CEA,26.0,1,26.0,Digital Wallet,Online,2024-05-23,True
6082,TXN_8103030,Cust_3,Furniture,Item_11_FUR,20.0,4,80.0,Cash,Online,2024-08-27,False
5245,TXN_1229733,Cust_4,Food,Item_3_FOOD,8.0,6,48.0,Digital Wallet,Online,2024-04-17,False

In [55]:
print(df["Category"].unique())

['Patisserie' 'Beverages' 'Computers and electric accessories' 'Furniture'
 'Food' 'Butchers' 'Milk Products' 'Electric household essentials']

In [56]:
df[df["Customer ID"]=="Cust_121"]

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
10959,TXN_1374187,Cust_121,Beverages,Item_11_BEV,20.0,5,100.0,Cash,In-store,2024-05-03,True

In [57]:
ts=df["Total Spent"].value_counts(normalize=True)*100
print(ts)

Total Spent
129.65    4.803181
40.00     1.113320
80.00     0.986083
25.00     0.970179
140.00    0.938370
            ...
129.50    0.198807
85.00     0.190855
274.50    0.190855
37.00     0.174950
166.50    0.135189
Name: proportion, Length: 228, dtype: float64

In [63]:
pd.to_numeric(df["Quantity"], errors="coerce").isna().sum()

np.int64(0)

In [65]:
df[pd.to_numeric(df["Total Spent"], errors="coerce").isna()]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Category, Item, Price Per Unit, Quantity, Total Spent, Payment Method, Location, Transaction Date, Discount Applied]
Index: []

In [66]:
df.to_csv("new2_retail_data.csv",index=False)

In [69]:
# Check if there are rows where (Price * Qty) != Total Spent
discrepancies = df[df['Price Per Unit'] * df['Quantity'] != df['Total Spent']]
print(len(discrepancies))

0

In [68]:
df['Total Spent'] = df['Price Per Unit'] * df['Quantity']

In [70]:
df.to_csv("new_retail.csv",index=False)